// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Permission } from '../../../api/fbs/common/permission.js';


export class RoleCreateRequest implements flatbuffers.IUnpackableObject<RoleCreateRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoleCreateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoleCreateRequest(bb:flatbuffers.ByteBuffer, obj?:RoleCreateRequest):RoleCreateRequest {
  return (obj || new RoleCreateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoleCreateRequest(bb:flatbuffers.ByteBuffer, obj?:RoleCreateRequest):RoleCreateRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoleCreateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

permissions(index: number):Permission|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

permissionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

permissionsArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startRoleCreateRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addPermissions(builder:flatbuffers.Builder, permissionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, permissionsOffset, 0);
}

static createPermissionsVector(builder:flatbuffers.Builder, data:Permission[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPermissionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endRoleCreateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

static createRoleCreateRequest(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, permissionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoleCreateRequest.startRoleCreateRequest(builder);
  RoleCreateRequest.addName(builder, nameOffset);
  RoleCreateRequest.addPermissions(builder, permissionsOffset);
  return RoleCreateRequest.endRoleCreateRequest(builder);
}

unpack(): RoleCreateRequestT {
  return new RoleCreateRequestT(
    this.name(),
    this.bb!.createScalarList<Permission>(this.permissions.bind(this), this.permissionsLength())
  );
}


unpackTo(_o: RoleCreateRequestT): void {
  _o.name = this.name();
  _o.permissions = this.bb!.createScalarList<Permission>(this.permissions.bind(this), this.permissionsLength());
}
}

export class RoleCreateRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public permissions: (Permission)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const permissions = RoleCreateRequest.createPermissionsVector(builder, this.permissions);

  return RoleCreateRequest.createRoleCreateRequest(builder,
    name,
    permissions
  );
}
}
