// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class UserCreateRequest implements flatbuffers.IUnpackableObject<UserCreateRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserCreateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserCreateRequest(bb:flatbuffers.ByteBuffer, obj?:UserCreateRequest):UserCreateRequest {
  return (obj || new UserCreateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserCreateRequest(bb:flatbuffers.ByteBuffer, obj?:UserCreateRequest):UserCreateRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserCreateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

email():string|null
email(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
email(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

initialPassword():string|null
initialPassword(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
initialPassword(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

roleIds(index: number):string
roleIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
roleIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

roleIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startUserCreateRequest(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addEmail(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, emailOffset, 0);
}

static addInitialPassword(builder:flatbuffers.Builder, initialPasswordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, initialPasswordOffset, 0);
}

static addRoleIds(builder:flatbuffers.Builder, roleIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, roleIdsOffset, 0);
}

static createRoleIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRoleIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endUserCreateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  builder.requiredField(offset, 6) // email
  builder.requiredField(offset, 8) // initial_password
  return offset;
}

static createUserCreateRequest(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, emailOffset:flatbuffers.Offset, initialPasswordOffset:flatbuffers.Offset, roleIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  UserCreateRequest.startUserCreateRequest(builder);
  UserCreateRequest.addName(builder, nameOffset);
  UserCreateRequest.addEmail(builder, emailOffset);
  UserCreateRequest.addInitialPassword(builder, initialPasswordOffset);
  UserCreateRequest.addRoleIds(builder, roleIdsOffset);
  return UserCreateRequest.endUserCreateRequest(builder);
}

unpack(): UserCreateRequestT {
  return new UserCreateRequestT(
    this.name(),
    this.email(),
    this.initialPassword(),
    this.bb!.createScalarList<string>(this.roleIds.bind(this), this.roleIdsLength())
  );
}


unpackTo(_o: UserCreateRequestT): void {
  _o.name = this.name();
  _o.email = this.email();
  _o.initialPassword = this.initialPassword();
  _o.roleIds = this.bb!.createScalarList<string>(this.roleIds.bind(this), this.roleIdsLength());
}
}

export class UserCreateRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public email: string|Uint8Array|null = null,
  public initialPassword: string|Uint8Array|null = null,
  public roleIds: (string)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const email = (this.email !== null ? builder.createString(this.email!) : 0);
  const initialPassword = (this.initialPassword !== null ? builder.createString(this.initialPassword!) : 0);
  const roleIds = UserCreateRequest.createRoleIdsVector(builder, builder.createObjectOffsetList(this.roleIds));

  return UserCreateRequest.createUserCreateRequest(builder,
    name,
    email,
    initialPassword,
    roleIds
  );
}
}
