// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class UserAdminPasswordResetRequest implements flatbuffers.IUnpackableObject<UserAdminPasswordResetRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserAdminPasswordResetRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserAdminPasswordResetRequest(bb:flatbuffers.ByteBuffer, obj?:UserAdminPasswordResetRequest):UserAdminPasswordResetRequest {
  return (obj || new UserAdminPasswordResetRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserAdminPasswordResetRequest(bb:flatbuffers.ByteBuffer, obj?:UserAdminPasswordResetRequest):UserAdminPasswordResetRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserAdminPasswordResetRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

newPassword():string|null
newPassword(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
newPassword(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startUserAdminPasswordResetRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNewPassword(builder:flatbuffers.Builder, newPasswordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, newPasswordOffset, 0);
}

static endUserAdminPasswordResetRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // new_password
  return offset;
}

static createUserAdminPasswordResetRequest(builder:flatbuffers.Builder, newPasswordOffset:flatbuffers.Offset):flatbuffers.Offset {
  UserAdminPasswordResetRequest.startUserAdminPasswordResetRequest(builder);
  UserAdminPasswordResetRequest.addNewPassword(builder, newPasswordOffset);
  return UserAdminPasswordResetRequest.endUserAdminPasswordResetRequest(builder);
}

unpack(): UserAdminPasswordResetRequestT {
  return new UserAdminPasswordResetRequestT(
    this.newPassword()
  );
}


unpackTo(_o: UserAdminPasswordResetRequestT): void {
  _o.newPassword = this.newPassword();
}
}

export class UserAdminPasswordResetRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public newPassword: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const newPassword = (this.newPassword !== null ? builder.createString(this.newPassword!) : 0);

  return UserAdminPasswordResetRequest.createUserAdminPasswordResetRequest(builder,
    newPassword
  );
}
}
