// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { ProductCreateRequest, ProductCreateRequestT } from './product/product-create-request.js';
export { ProductListResponse, ProductListResponseT } from './product/product-list-response.js';
export { ProductResponse, ProductResponseT } from './product/product-response.js';
export { ProductUpdateRequest, ProductUpdateRequestT } from './product/product-update-request.js';
