// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ContainerStatus {
  Empty = 0,
  Loading = 1,
  Sealed = 2,
  InTransit = 3
}
