// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RiskClass {
  Class1Explosives = 0,
  Class2Gases = 1,
  Class3FlammableLiquids = 2,
  Class4FlammableSolids = 3,
  Class5OxidizingSubstances = 4,
  Class6ToxicSubstances = 5,
  Class7RadioactiveMaterials = 6,
  Class8CorrosiveSubstances = 7,
  Class9Miscellaneous = 8,
  None = 9
}
