// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TelemetryEvent {
  Create = 0,
  Load = 1,
  Unload = 2,
  Seal = 3,
  Dispatch = 4
}
