// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RiskClass } from '../../../api/fbs/common/risk-class.js';


export class ProductResponse implements flatbuffers.IUnpackableObject<ProductResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProductResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProductResponse(bb:flatbuffers.ByteBuffer, obj?:ProductResponse):ProductResponse {
  return (obj || new ProductResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProductResponse(bb:flatbuffers.ByteBuffer, obj?:ProductResponse):ProductResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProductResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

density():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

riskClass():RiskClass {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RiskClass.Class1Explosives;
}

static startProductResponse(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addDensity(builder:flatbuffers.Builder, density:number) {
  builder.addFieldFloat64(2, density, 0.0);
}

static addRiskClass(builder:flatbuffers.Builder, riskClass:RiskClass) {
  builder.addFieldInt8(3, riskClass, RiskClass.Class1Explosives);
}

static endProductResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProductResponse(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, density:number, riskClass:RiskClass):flatbuffers.Offset {
  ProductResponse.startProductResponse(builder);
  ProductResponse.addId(builder, idOffset);
  ProductResponse.addName(builder, nameOffset);
  ProductResponse.addDensity(builder, density);
  ProductResponse.addRiskClass(builder, riskClass);
  return ProductResponse.endProductResponse(builder);
}

unpack(): ProductResponseT {
  return new ProductResponseT(
    this.id(),
    this.name(),
    this.density(),
    this.riskClass()
  );
}


unpackTo(_o: ProductResponseT): void {
  _o.id = this.id();
  _o.name = this.name();
  _o.density = this.density();
  _o.riskClass = this.riskClass();
}
}

export class ProductResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null,
  public density: number = 0.0,
  public riskClass: RiskClass = RiskClass.Class1Explosives
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);

  return ProductResponse.createProductResponse(builder,
    id,
    name,
    this.density,
    this.riskClass
  );
}
}
