// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Permission } from '../../../api/fbs/common/permission.js';


export class RoleResponse implements flatbuffers.IUnpackableObject<RoleResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoleResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoleResponse(bb:flatbuffers.ByteBuffer, obj?:RoleResponse):RoleResponse {
  return (obj || new RoleResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoleResponse(bb:flatbuffers.ByteBuffer, obj?:RoleResponse):RoleResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoleResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

userCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

permissions(index: number):Permission|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

permissionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

permissionsArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startRoleResponse(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addUserCount(builder:flatbuffers.Builder, userCount:number) {
  builder.addFieldInt32(2, userCount, 0);
}

static addPermissions(builder:flatbuffers.Builder, permissionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, permissionsOffset, 0);
}

static createPermissionsVector(builder:flatbuffers.Builder, data:Permission[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPermissionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endRoleResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoleResponse(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, userCount:number, permissionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoleResponse.startRoleResponse(builder);
  RoleResponse.addId(builder, idOffset);
  RoleResponse.addName(builder, nameOffset);
  RoleResponse.addUserCount(builder, userCount);
  RoleResponse.addPermissions(builder, permissionsOffset);
  return RoleResponse.endRoleResponse(builder);
}

unpack(): RoleResponseT {
  return new RoleResponseT(
    this.id(),
    this.name(),
    this.userCount(),
    this.bb!.createScalarList<Permission>(this.permissions.bind(this), this.permissionsLength())
  );
}


unpackTo(_o: RoleResponseT): void {
  _o.id = this.id();
  _o.name = this.name();
  _o.userCount = this.userCount();
  _o.permissions = this.bb!.createScalarList<Permission>(this.permissions.bind(this), this.permissionsLength());
}
}

export class RoleResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null,
  public userCount: number = 0,
  public permissions: (Permission)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const permissions = RoleResponse.createPermissionsVector(builder, this.permissions);

  return RoleResponse.createRoleResponse(builder,
    id,
    name,
    this.userCount,
    permissions
  );
}
}
